#language:
#- objective-c
os:
  - osx
env:
  global:
  - REPO_DIR=ecell4
  matrix:
  - VERSION=3.6.0
install:
  - source terryfy/travis_tools.sh
  - export CC=clang; export CXX=clang++
  - get_python_environment macpython $VERSION venv
#  # Update to latest wheel package for Python 3.6
  - pip install -U wheel delocate cython
  - brew update; brew install gsl homebrew/versions/boost159 homebrew/science/hdf5
  - cd $REPO_DIR; BOOST_INCLUDEDIR=/usr/local/opt/boost159/include cmake -DNO_SHARED:BOOL=1 .
  - cd ..; cp config.h $REPO_DIR/ecell4/core; cd $REPO_DIR
  - make > /dev/null
  - delocate-listdeps python/dist/*.whl # lists library dependencies
  - delocate-wheel python/dist/*.whl # copies library dependencies into wheel
#  - delocate-addplat --rm-orig -x 10_9 -x 10_10 python/dist/*.whl
  - pip install python/dist/*.whl
  - cd ../..

script:
#  - python -c "from ecell4 import core"
  - pwd
  - ls
#  - unset CC CXX # reset to default compilation for deploy modules

after_script:
  - sleep 300

deploy:
  provider: releases
  api_key:
    secure: Oz0EVQ0VDKNhE4k7dr+plJvUZwN6pkfYGOXOKUCRIjtA+MLKx3lY5++83F72nKqF6Y1ud6N7Fu/dAUzslcXZIKJ/fQ25bzRc6FfUEFFkS0DmqZTQY2i1S0s+li8J4u9LGPQndVRUg7Z4IXkcyVnogtnYdmjuwfC1h5njIShiR6LUj9nIC4WpSK1IXrH1IhV0sGxr3WynmYp7H5tbAuZ1hUnG5YQ3T0eOoD6HaNo0kRdnCMPRebJ16YrbZ2rBcHMYu2WQM36awxQfNDyV8w/4iRVL/2knRd9eDXrKkv2TsUcD0ZoSz6iuGwBRxkIZLL9nDJIW+QXM6TJdwTfPKynR/vj/fp+V4wN+vFsvM7mQIVfzhh6hbIbPBdFDtClKz7Tj6ekmDOQvTfC+Auqxzq9Q9lQKEkFxhDNGZvjtze9/2qjktKhD8Hl0oDEcUMeAYRgIk/x1e/Ro7fWJTDPoQW4jPTlhJKCddrXF5+RxyoNqx1VF65bgrSfTSNaqkZvlRQTg9y1xloaiV7jHnNDuZG3NQ2qweDiqEiHro2+KXef7FOtHguPEsnSgqnSkzd50q8eklAZn2elYWRBqLQ0FQFdYxlXGhClxiuiU1zL6JgppDNM1QLUDgCPePlMhJtx/QUVSmfIaGc6r62Z7eMH54ShIZDE0j62GOi+iNUzH0rp+tk0=
  file_glob: true
  file: "ecell4/python/dist/*.whl"
  skip_cleanup: true
  overwrite: true
  on:
    repo: ecell/ecell4-wheels
#    all_branches: true
    tags: true

after_deploy:
  - sleep 300
