language:
- objective-c
env:
  global:
  - REPO_DIR=ecell4
  matrix:
  - VERSION=2.7.11
#   - VERSION=3.3.5
#   - VERSION=3.4.3
  - VERSION=3.5.1
install:
  - source terryfy/travis_tools.sh
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython $VERSION venv
  # Update to latest wheel package for Python 3.5
  - pip install -U wheel
  - pip install delocate
  - pip install cython
  - brew update
  - brew upgrade cmake
  #- brew upgrade boost
  - brew install gsl
  - brew install homebrew/versions/boost159
  - brew install homebrew/science/hdf5
  - cd $REPO_DIR
  - BOOST_INCLUDEDIR=/usr/local/opt/boost159/include cmake .
#  - make BesselTables
  - cd ..
  - cp config.h $REPO_DIR/ecell4/core
  - cd $REPO_DIR/python
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ../..

script:
  - python -c "from ecell4 import core"
  - unset CC CXX # reset to default compilation for deploy modules

#deploy:
#  provider: pypi
#  user: kozo2
#  password:
#    secure: MrKse0WVELuWuDG8RIAOlxmZBti/8sNsUjUDY7UiGx7WGfrEu3WCJ6/+t2UuLH+eOQqukNFXkfuVf2NfwTjv0ujX+dpfSViDb8tyxh2OC5hH8JvEe+H1EO9uwLVCS6ynsqeOND8bkOGIkxYGzpwYR18Y5T5IcvunckQ$
#  file_glob: true
#  file: ecell4/python/dist/*.whl
#  skip_cleanup: true
#  overwrite: true
#  on:
#    tags: true
